In [2]:
pip install flask



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip



  Obtaining dependency information for flask from https://files.pythonhosted.org/packages/61/80/ffe1da13ad9300f87c93af113edd0638c75138c42a0994becfacac078c06/flask-3.0.3-py3-none-any.whl.metadata
  Using cached flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
  Obtaining dependency information for Werkzeug>=3.0.0 from https://files.pythonhosted.org/packages/4b/84/997bbf7c2bf2dc3f09565c6d0b4959fefe5355c18c4096cfd26d83e0785b/werkzeug-3.0.4-py3-none-any.whl.metadata
  Using cached werkzeug-3.0.4-py3-none-any.whl.metadata (3.7 kB)
  Obtaining dependency information for itsdangerous>=2.1.2 from https://files.pythonhosted.org/packages/04/96/92447566d16df59b2a776c0fb82dbc4d9e07cd95062562af01e408583fc4/itsdangerous-2.2.0-py3-none-any.whl.metadata
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
  Obtaining dependency information for click>=8.1.3 from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none

In [14]:
pip install cv2


Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [15]:
pip install pytesseract


  Obtaining dependency information for pytesseract from https://files.pythonhosted.org/packages/7a/33/8312d7ce74670c9d39a532b2c246a853861120486be9443eebf048043637/pytesseract-0.3.13-py3-none-any.whl.metadata
  Using cached pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
  Obtaining dependency information for Pillow>=8.0.0 from https://files.pythonhosted.org/packages/74/0a/d4ce3c44bca8635bd29a2eab5aa181b654a734a29b263ca8efe013beea98/pillow-10.4.0-cp312-cp312-win_amd64.whl.metadata
  Using cached pillow-10.4.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Using cached pytesseract-0.3.13-py3-none-any.whl (14 kB)
Using cached pillow-10.4.0-cp312-cp312-win_amd64.whl (2.6 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install pytesseract

  Obtaining dependency information for pytesseract from https://files.pythonhosted.org/packages/7a/33/8312d7ce74670c9d39a532b2c246a853861120486be9443eebf048043637/pytesseract-0.3.13-py3-none-any.whl.metadata
  Using cached pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
  Obtaining dependency information for Pillow>=8.0.0 from https://files.pythonhosted.org/packages/74/0a/d4ce3c44bca8635bd29a2eab5aa181b654a734a29b263ca8efe013beea98/pillow-10.4.0-cp312-cp312-win_amd64.whl.metadata
  Using cached pillow-10.4.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Using cached pytesseract-0.3.13-py3-none-any.whl (14 kB)
Using cached pillow-10.4.0-cp312-cp312-win_amd64.whl (2.6 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install opencv-python


  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/ec/6c/fab8113424af5049f85717e8e527ca3773299a3c6b02506e66436e19874f/opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl.metadata
  Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
  Obtaining dependency information for numpy>=1.21.2 from https://files.pythonhosted.org/packages/8c/bf/d9d214a9dff020ad1663f1536f45d34e052e4c7f630c46cd363e785e3231/numpy-2.1.0-cp312-cp312-win_amd64.whl.metadata
  Using cached numpy-2.1.0-cp312-cp312-win_amd64.whl.metadata (59 kB)
Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)
Using cached numpy-2.1.0-cp312-cp312-win_amd64.whl (12.6 MB)



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
pip install pandas



  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/22/a5/a0b255295406ed54269814bc93723cfd1a0da63fb9aaf99e1364f07923e5/pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata
  Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/9c/3d/a121f284241f08268b21359bd425f7d4825cffc5ac5cd0e1b3d82ffd2b10/pytz-2024.1-py2.py3-none-any.whl.metadata
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/65/58/f9c9e6be752e9fcb8b6a0ee9fb87e6e7a1f6bcab2cdc73f02bb7ba91ada0/tzdata-2024.1-py2.py3-none-any.whl.metadata
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl (11.5 MB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
from flask import Flask, jsonify, request
import pandas as pd
import cv2
import pytesseract
import  json
app = Flask(__name__)

@app.route('/')
def welcome_page():
    return 'Welcome to Data Extraction PRAVEEN App'
     
@app.route('/dataextractor', methods=['GET'])
def get_dict_json():
    #file = request.files['image']
    #file.save('static/' + file.filename)
   
    pytesseract.pytesseract.tesseract_cmd =r'C:\Users\user\PycharmProjects\data_extraction\tesseract-ocr\tesseract.exe'
    image=cv2.imread(r'C:\Users\user\PycharmProjects\data_extraction\rdx.png')
    text = pytesseract.image_to_string(image)
    variable=text.split("Total")
    variable
    lines = variable[1].split('\n')
    filtered_lines = [line for line in lines if "Subtotal" not in line and "Tax" not in line]
    filtered_lines
    filtered_data = [line for line in filtered_lines if line.strip()]
    filtered_data
    item_names = []
    quantities = []
    prices = []
    total = []
   
    for item in filtered_data :
        components = item.split()
        print(components)
       
        item_names.append(' '.join(components [0:3]))
        quantities.append(components[3])
        prices.append(components[-2])
        total.append(components[-1])
   
    data = {
        'Item name':item_names,
        'Quantities':quantities,
        'Prices':prices,
        'Total':total,
    }
    df = pd.DataFrame(data)
    df
   
    json_data = df.to_json()
    json_data
    dict_=json.loads(json_data)
    dict_['Item name']
       
    return dict_

if __name__ == '__main__':
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit


out [[[ 60  60  60]
  [ 60  60  60]
  [ 60  60  60]
  ...
  [ 59  59  59]
  [ 59  59  59]
  [ 59  59  59]]

 [[ 70  71  68]
  [ 70  71  68]
  [ 70  71  68]
  ...
  [ 70  71  68]
  [ 70  71  68]
  [ 70  71  68]]

 [[240 245 245]
  [240 245 245]
  [240 245 245]
  ...
  [240 245 245]
  [240 245 245]
  [240 245 245]]

 ...

 [[240 245 245]
  [240 245 245]
  [240 245 245]
  ...
  [240 245 245]
  [240 245 245]
  [240 245 245]]

 [[240 245 245]
  [240 245 245]
  [240 245 245]
  ...
  [240 245 245]
  [240 245 245]
  [240 245 245]]

 [[240 245 245]
  [240 245 245]
  [240 245 245]
  ...
  [240 245 245]
  [240 245 245]
  [240 245 245]]]


127.0.0.1 - - [29/Aug/2024 15:27:39] "GET /dataextractor HTTP/1.1" 200 -


['Eggshell', 'Camisole', 'Top', '1', '$123', '$123']
['Cuban', 'Collar', 'Shirt.', '2', '$127', '$254']
['Floral', 'Cotton', 'Dress.', '1', '$123', '$123']
